// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvXYj7MtD_dimdLGLlhlX5dJBR3dk76ig',
    appId: '1:605783325921:web:71e7c28e184af4a4f5cba0',
    messagingSenderId: '605783325921',
    projectId: 'pkm-tembelang-1eb0d',
    authDomain: 'pkm-tembelang-1eb0d.firebaseapp.com',
    databaseURL: 'https://pkm-tembelang-1eb0d-default-rtdb.firebaseio.com',
    storageBucket: 'pkm-tembelang-1eb0d.firebasestorage.app',
    measurementId: 'G-GEZ27X3XYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvH32u-gNRlNi7bMiQwzj0RXAud60kf2I',
    appId: '1:605783325921:android:e4dfbded8225dce0f5cba0',
    messagingSenderId: '605783325921',
    projectId: 'pkm-tembelang-1eb0d',
    databaseURL: 'https://pkm-tembelang-1eb0d-default-rtdb.firebaseio.com',
    storageBucket: 'pkm-tembelang-1eb0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDrfXOWCZWL35vVhEasi0jviSBh646jtA',
    appId: '1:605783325921:ios:4be8a0866f088d8bf5cba0',
    messagingSenderId: '605783325921',
    projectId: 'pkm-tembelang-1eb0d',
    databaseURL: 'https://pkm-tembelang-1eb0d-default-rtdb.firebaseio.com',
    storageBucket: 'pkm-tembelang-1eb0d.firebasestorage.app',
    iosBundleId: 'com.example.uasMedical',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDrfXOWCZWL35vVhEasi0jviSBh646jtA',
    appId: '1:605783325921:ios:4be8a0866f088d8bf5cba0',
    messagingSenderId: '605783325921',
    projectId: 'pkm-tembelang-1eb0d',
    databaseURL: 'https://pkm-tembelang-1eb0d-default-rtdb.firebaseio.com',
    storageBucket: 'pkm-tembelang-1eb0d.firebasestorage.app',
    iosBundleId: 'com.example.uasMedical',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvXYj7MtD_dimdLGLlhlX5dJBR3dk76ig',
    appId: '1:605783325921:web:8ef965703c76783cf5cba0',
    messagingSenderId: '605783325921',
    projectId: 'pkm-tembelang-1eb0d',
    authDomain: 'pkm-tembelang-1eb0d.firebaseapp.com',
    databaseURL: 'https://pkm-tembelang-1eb0d-default-rtdb.firebaseio.com',
    storageBucket: 'pkm-tembelang-1eb0d.firebasestorage.app',
    measurementId: 'G-7FCHJGFFRF',
  );
}
